<?php
session_start();
if(!isset($_SESSION['email'])){
    header("location:Login.php");
    exit;
}
session_start();
$_SESSION['email']='';
session_destroy();
header("location:Login.php");
exit;
 ?>
